name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
    steps:
    - uses: actions/checkout@v3

    # Backend
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o out

    # Frontend
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
    - name: Build frontend
      run: |
        cd frontend
        npm run build

    # Docker (опционально)
    - name: Build Docker image
      run: docker build -t meeting-scheduler . 